# Generated by Django 4.1.1 on 2023-03-15 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_comment_autor_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AddField(
            model_name='comment',
            name='registered_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='unregistered_author',
            field=models.CharField(blank=True, default='anonimus', max_length=30, null=True, verbose_name='Незарегистрированный автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='registered_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='unregistered_author',
            field=models.CharField(blank=True, default='anonimus', max_length=30, null=True, verbose_name='Незарегистрированный автор'),
        ),
    ]
