# Generated by Django 4.1.1 on 2023-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_registered_author_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonimus_name',
            field=models.CharField(default='Аноним', max_length=10, verbose_name='Аноним'),
        ),
    ]
