# Generated by Django 4.1.1 on 2023-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_anonimus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonimus_name',
            field=models.CharField(default='Аноним', max_length=10, verbose_name='Аноним'),
        ),
    ]
