# Generated by Django 4.1.1 on 2023-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_anonimus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='anonimus_name',
            field=models.CharField(blank=True, default='Аноним', max_length=10, verbose_name='Аноним'),
        ),
    ]
